apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: linkki-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkki-publisher
  template:
    metadata:
      labels:
        app: linkki-publisher
    spec:
      containers:
      - name: gtfsrthttp2mqtt
        image: hsldevcom/gtfsrthttp2mqtt:latest
        imagePullPolicy: "Always"
        env:
        - name: MQTT_BROKER_URL
          value: "emqx"
        - name: USERNAME
          valueFrom:
           secretKeyRef:
            name: admin-us-ps
            key: username.txt
        - name: PASSWORD
          valueFrom:
           secretKeyRef:
             name: admin-us-ps
             key: passwrod.txt
        - name: FEED_NAME
          value: "LINKKI"
        - name: FEED_TYPE
          value: "vp"
        - name: FEED_URL
          valueFrom:
           configMapKeyRef:
             name: feed-urls
             key: linkki
        - name: INTERVAL
          value: "10"
---  
apiVersion: v1
kind: Service
metadata:
  name: linkki-publisher
spec:
  ports:
  - name: "linkki-publisher-service"
    port: 3001
  selector:
    app: linkki-publisher
---