apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tampere-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tampere-publisher
  template:
    metadata:
      labels:
        app: tampere-publisher
    spec:
      containers:
      - name: gtfsrthttp2mqtt
        image: hsldevcom/gtfsrthttp2mqtt:latest
        imagePullPolicy: "Always"
        env:
        - name: MQTT_BROKER_URL
          value: "emqx"
        - name: USERNAME
          valueFrom:
           secretKeyRef:
             name: admin-us-ps
             key: username.txt
        - name: PASSWORD
          valueFrom:
           secretKeyRef:
             name: admin-us-ps
             key: passwrod.txt
        - name: FEED_NAME
          value: "tampere"
        - name: FEED_TYPE
          value: "vp"
        - name: FEED_URL     
          valueFrom:
           configMapKeyRef:
             name: feed-urls
             key: tampere
        - name: INTERVAL
          value: "10"
        - name: ROUTE_ID_REMOVE_LAST
          value: "4"

---  
apiVersion: v1
kind: Service
metadata:
  name: tampere-publisher
spec:
  ports:
  - name: "tampere-publisher-service"
    port: 3000
  selector:
    app: tampere-publisher
---    