apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  ports:
  - port: 32333
    nodePort: 32333
    targetPort:  emqx-dashboard
    protocol: TCP
  selector:
    app: emqx
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emqx
  labels:
        app: emqx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:latest
        ports:
        - name: emqx-dashboard
          containerPort: 18083
        env:
        - name: EMQX_CLUSTER__DISCOVERY
          value: k8s
        - name: EMQX_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__APISERVER
          value: http://172.31.19.161:8080
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: default
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
          value: ip
        - name: EMQX_CLUSTER__K8S__APP_NAME
          value: emqx
        - name: EMQX_AUTH__USER__1__username
          value: admin
        - name: EMQX_AUTH__USER__1__password
          value: emqxadminpassword
        - name: EMQX_AUTH__USER__2__username
          value: user
        - name: EMQX_AUTH__USER__2__password
          value: userpass
        - name: EMQX_MQTT__ALLOW_ANONYMOUS
          value: false
        - name: EMQX_LOADED_PLUGINS
          value: emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_username
        tty: true