---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-tcp
  namespace: default
data:
  "1883": "default/emqx:1883"
  "8883": "default/emqx:1883"
  "80": "default/emqx:8083"
  "443": "default/emqx:8083"
---  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-ingress
  namespace: default
---
apiVersion: v1
data:
    dynamic-scaling: "true"
    backend-server-slots-increment: "4"
    timeout-connect: "120s"
    timeout-client: "200s"
    timeout-server: "120s"
    max-connections: "500000"
    ssl-dh-default-max-size: "2048"
    nbroc-ssl: "2"
    cpu-map: "1 0"
    cpu-map: "2 1"

kind: ConfigMap
metadata:
  name: haproxy-configmap
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      serviceAccountName: haproxy-ingress
      containers:
      - name: haproxy-ingress
        image: quay.io/jcmoraisjr/haproxy-ingress
        args:
        - --default-backend-service=$(POD_NAMESPACE)/emqx
        - --default-ssl-certificate=default/tls-sceret
        - --configmap=$(POD_NAMESPACE)/haproxy-configmap
        - --tcp-services-configmap=$(POD_NAMESPACE)/haproxy-tcp
        - --reload-strategy=native
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1936
        - name: mqtt-public
          containerPort: 1883
        - name: mqtt-testing
          containerPort: 8883
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: default
spec:
  ports:
  - port: 1883
    name: mqtt-public
    targetPort: 1883  
#    protocol: TCP
  - port: 8883
    name: mqtt-tls
    targetPort: 8883
  - port: 80
    name: websocket
#    targetPort: 8083
  - port: 443
    name: secwebsocket
#    targetPort: 8083   
  loadBalancerIP: 13.95.195.91  
  type: LoadBalancer
  selector:
    run: haproxy-ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
spec:
  rules:
  - host: dev-mqtt.lmj.fi
    http:
      paths:
      - path: /
        backend:
          serviceName: emqx
          servicePort: 8083	