---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      volumes:
      - name: secret-mount
        secret:
           secretName: star-lmj-pem
      - name: digisecret-mount
        secret:
           secretName: star-digitransit-v2-pem
      - name: jyvaskylasecret-mount
        secret:
           secretName: star-jyvaskyla-v3-pem
      - name: haconfig
        configMap: 
           name: haproxy-config-h72d97c6b5
      containers:
      - name: haproxy
        image: haproxy:2.2.0
        ports:
        - name: https
          containerPort: 443
        volumeMounts:
        - name: digisecret-mount
          mountPath: "/etc/ssl/private/digitransit"
          readOnly: true
        - name: jyvaskylasecret-mount
          mountPath: "/etc/ssl/private/jyvaskyla"
          readOnly: true
        - name: haconfig
          mountPath: "/usr/local/etc/haproxy"
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: default
spec:
  ports:
  - port: 8080
    name: virtualmonitor
  - port: 443
    name: secwebsocket
#    targetPort: 8083
  type: LoadBalancer
  selector:
    run: haproxy-ingress
---
