apiVersion: apps/v1
kind: Deployment
metadata:
  name: lahti-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lahti-publisher
  template:
    metadata:
      labels:
        app: lahti-publisher
    spec:
      containers:
      - name: gtfsrthttp2mqtt
        image: hsldevcom/gtfsrthttp2mqtt:latest
        imagePullPolicy: "Always"
        env:
        - name: MQTT_BROKER_URL
          value: "emqx"
        - name: USERNAME
          valueFrom:
           secretKeyRef:
             name: admin-us-ps
             key: username.txt
        - name: PASSWORD
          valueFrom:
           secretKeyRef:
             name: admin-us-ps
             key: passwrod.txt
        - name: FEED_NAME
          value: "Lahti"
        - name: FEED_TYPE
          value: "vp"
        - name: FEED_URL
          valueFrom:
           configMapKeyRef:
             name: feed-urls
             key: lahti
        - name: INTERVAL
          value: "10"
